# Generated by Django 4.1.1 on 2022-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=1000, verbose_name='Исходная ссылка')),
                ('shortlink_url', models.CharField(max_length=30, verbose_name='Сокращенная ссылка')),
            ],
            options={
                'verbose_name': 'Cсылка',
                'verbose_name_plural': 'Cсылки',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
