# Generated by Django 4.1.1 on 2022-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_link_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortlink_url',
            field=models.CharField(max_length=5, verbose_name='Сокращенная ссылка'),
        ),
    ]
